name: arweave update

# Controls when the action will run.
on:
  schedule:
    - cron: "0 */4 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: run-arweave-import
  cancel-in-progress: false

jobs:
  run-arweave-import:
    name: run-arweave-import
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install node v24
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: run importer
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CRYPTOCOMPARE_API_KEY: ${{ secrets.CRYPTOCOMPARE_API_KEY }}
        run: yarn cmd cmd/arweave.ts
