name: filecoin update

# Controls when the action will run.
on:
  schedule:
    - cron: "0 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: run-filecoin-import
  cancel-in-progress: false

jobs:
  run-filecoin-import:
    name: run-filecoin-import
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: yarn install
        run: yarn install
      - name: install typescript
        run: npm install -g typescript@4.5.5
      - name: change directory
        run: cd ./cmd
      - name: compile
        run: tsc ./cmd/filecoin.ts --esModuleInterop
      - name: list files
        run: ls ./cmd
      - name: run
        run: node ./cmd/filecoin.js
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TOKENTERMINAL_API_KEY: ${{ secrets.TOKENTERMINAL_API_KEY }}
