name: filecoin update

# Controls when the action will run.
on:
  schedule:
    - cron: "0 */4 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: run-filecoin-import
  cancel-in-progress: false

jobs:
  run-filecoin-import:
    name: run-filecoin-import
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install node v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: run importer
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SPACESCOPE_API_KEY: ${{ secrets.SPACESCOPE_API_KEY }}
        run: yarn cmd cmd/filecoin.ts
